stages:
  preprocess:
    foreach: ${matrix.add_response_token}
    do:
      cmd: >
        python preprocess_dataset.py 
        --model_name ${model_name} 
        --task_type ${task_type} 
        --data_size ${data_size}
        --add_response_token ${item}
        --seed 42
        ${ all_models ? '--all_models' : ''}
        ${ multi_round ? '--multi_round' : ''}
        ${ head_tail ? '--head_tail' : ''}
      deps:
        - preprocess_dataset.py
      params:
        - params.yaml:preprocess
        - params.yaml:matrix.add_response_token
      outs:
        - ${dataset_path}_preview${item}:
            cache: true
            persist: true

  train:
    foreach: ${matrix.add_response_token}
    do:
      cmd: >
        python latency_prediction.py 
        --model_name ${model_name}
        --task_type ${task_type}
        --data_size ${data_size}
        --add_response_token ${item}
        --seed 42
        ${ all_models ? '--all_models' : ''}
        ${ multi_round ? '--multi_round' : ''}
        ${ head_tail ? '--head_tail' : ''}
        ${ bert_tiny ? '--bert_tiny' : ''}
        ${ l1_loss ? '--l1_loss' : ''}
        ${ use_wandb ? '--use_wandb' : ''}
        ${ log_model ? '--log_model' : ''}
        --wandb_project ${wandb_project}
      deps:
        - latency_prediction.py
        - models.py
        - utils.py
        - train.py
        - evaluate.py
        - dataloading.py
        - logger.py
        - ${dataset_path}_preview${item}
      params:
        - params.yaml:train
        - params.yaml:matrix.add_response_token
      metrics:
        - ./metrics/${output_filename}_preview${item}.txt:
            cache: false
      outs:
        - ./models/${output_filename}_preview${item}.pth:
            cache: true
        - ./results/${output_filename}_preview${item}:
            cache: true 