stages:
  preprocess:
    foreach: [0, 1, 2, 3, 4, 5]
    do:
      cmd: >
        python preprocess_dataset.py 
        --model_name "vicuna-13b"
        --task_type 0
        --data_size 10
        --add_response_token ${item}
        --seed 42
      deps:
        - preprocess_dataset.py

  train:
    foreach: [0, 1, 2, 3, 4, 5]
    do:
      cmd: >
        python latency_prediction.py 
        --model_name "vicuna-13b"
        --task_type 0
        --data_size 10
        --add_response_token ${item}
        --seed 42
        --use_wandb
      deps:
        - latency_prediction.py
        - models.py
        - utils.py
        - train.py
        - evaluate.py
        - dataloading.py
        - logger.py
        - data/lmsys_first_round_data_vicuna-13b_preview${item}